Repository lazarnagulov/zbrinjavanje-zivotinja, pull requests merged in 2024-07, with the labels that each got.

#7 Repository with CRUD operations
  PetCenter/PetCenter/App.xaml.cs
  PetCenter/PetCenter/Domain/Model/Account.cs
  PetCenter/PetCenter/Domain/Model/Address.cs
  PetCenter/PetCenter/Domain/Model/Animal.cs
  PetCenter/PetCenter/Domain/Model/AnimalType.cs
  PetCenter/PetCenter/Domain/Model/Comment.cs
  PetCenter/PetCenter/Domain/Model/Offer.cs
  PetCenter/PetCenter/Domain/Model/Person.cs
  PetCenter/PetCenter/Domain/Model/Photo.cs
  PetCenter/PetCenter/Domain/Model/Post.cs
  PetCenter/PetCenter/Domain/Model/Request.cs
  PetCenter/PetCenter/Domain/Model/Review.cs
  PetCenter/PetCenter/Domain/RepositoryInterfaces/IAccountRepository.cs
  PetCenter/PetCenter/Domain/RepositoryInterfaces/IAnimalRepository.cs
  PetCenter/PetCenter/Domain/RepositoryInterfaces/IAnimalTypeRepository.cs
  PetCenter/PetCenter/Domain/RepositoryInterfaces/ICommentRepository.cs
  PetCenter/PetCenter/Domain/RepositoryInterfaces/ICrud.cs
  PetCenter/PetCenter/Domain/RepositoryInterfaces/IOfferRepository.cs
  PetCenter/PetCenter/Domain/RepositoryInterfaces/IPersonRepository.cs
  PetCenter/PetCenter/Domain/RepositoryInterfaces/IPostRepository.cs
  PetCenter/PetCenter/Domain/RepositoryInterfaces/IRequestRepository.cs
  PetCenter/PetCenter/Domain/State/Accepted.cs
  PetCenter/PetCenter/Domain/State/Adopted.cs
  PetCenter/PetCenter/Domain/State/Created.cs
  PetCenter/PetCenter/Domain/State/Declined.cs
  PetCenter/PetCenter/Domain/State/Hidden.cs
  PetCenter/PetCenter/Domain/State/OnHold.cs
  PetCenter/PetCenter/Domain/State/PostState.cs
  PetCenter/PetCenter/Domain/State/TemporaryAccommodation.cs
  PetCenter/PetCenter/Migrations/20240701100756_Initial.Designer.cs
  PetCenter/PetCenter/Migrations/20240701100756_Initial.cs
  PetCenter/PetCenter/Migrations/DataContextModelSnapshot.cs
  PetCenter/PetCenter/PetCenter.csproj
  PetCenter/PetCenter/Repository/AccountSqlRepository.cs
  PetCenter/PetCenter/Repository/AnimalSqlRepository.cs
  PetCenter/PetCenter/Repository/CommentSqlRepository.cs
  PetCenter/PetCenter/Repository/DataContext.cs
  PetCenter/PetCenter/Repository/OfferSqlRepository.cs
  PetCenter/PetCenter/Repository/PersonSqlRepository.cs
  PetCenter/PetCenter/Repository/PostSqlRepository.cs
  PetCenter/PetCenter/Repository/RequestSqlRepository.cs
  PetCenter/PetCenter/Repository/SqlRepository.cs
  doc/diagrams/diagrams.mdzip
  doc/specification/img/class.jpg
  scripts/ddl.sql
Labels: enhancement

#9 Login service
  PetCenter/PetCenter/App.xaml.cs
  PetCenter/PetCenter/Core/Service/LoginService.cs
  PetCenter/PetCenter/Core/Util/DatabaseCredentials.cs
  PetCenter/PetCenter/Core/Util/PasswordEncoder.cs
  PetCenter/PetCenter/Domain/Model/Account.cs
  PetCenter/PetCenter/Domain/RepositoryInterfaces/IAccountRepository.cs
  PetCenter/PetCenter/Domain/RepositoryInterfaces/ICrud.cs
  PetCenter/PetCenter/PetCenter.csproj
  PetCenter/PetCenter/Repository/AccountSqlRepository.cs
  PetCenter/PetCenter/Repository/AnimalSqlRepository.cs
  PetCenter/PetCenter/Repository/CommentSqlRepository.cs
  PetCenter/PetCenter/Repository/DataContext.cs
  PetCenter/PetCenter/Repository/OfferSqlRepository.cs
  PetCenter/PetCenter/Repository/PersonSqlRepository.cs
  PetCenter/PetCenter/Repository/PostSqlRepository.cs
  PetCenter/PetCenter/Repository/RequestSqlRepository.cs
  PetCenter/PetCenter/Repository/SqlRepository.cs
  PetCenter/PetCenter/WPF/Validation/EmailValidationRule.cs
  PetCenter/PetCenter/WPF/Validation/RequiredFieldValidationRule.cs
  PetCenter/PetCenter/WPF/ViewModelBase.cs
  PetCenter/PetCenter/WPF/ViewModels/AccountViewModel.cs
  scripts/ddl.sql
Labels: enhancement

#4 Add Dependency Injection
  PetCenter/PetCenter/App.xaml
  PetCenter/PetCenter/App.xaml.cs
  PetCenter/PetCenter/Core/Stores/NavigationStore.cs
  PetCenter/PetCenter/HostBuilders/AddRepositoriesExtension.cs
  PetCenter/PetCenter/HostBuilders/AddServicesExtension.cs
  PetCenter/PetCenter/HostBuilders/AddStoresExtension.cs
  PetCenter/PetCenter/HostBuilders/AddViewModelsExtension.cs
  PetCenter/PetCenter/HostBuilders/AddWindowsExtension.cs
  PetCenter/PetCenter/MainWindow.xaml
  PetCenter/PetCenter/PetCenter.csproj
  PetCenter/PetCenter/WPF/BaseViewModels/AccountViewModel.cs
  PetCenter/PetCenter/WPF/BaseViewModels/AddressViewModel.cs
  PetCenter/PetCenter/WPF/BaseViewModels/AnimalTypeViewModel.cs
  PetCenter/PetCenter/WPF/BaseViewModels/AnimalViewModel.cs
  PetCenter/PetCenter/WPF/BaseViewModels/CommentViewModel.cs
  PetCenter/PetCenter/WPF/BaseViewModels/OfferViewModel.cs
  PetCenter/PetCenter/WPF/BaseViewModels/PersonViewModel.cs
  PetCenter/PetCenter/WPF/BaseViewModels/PhotoViewModel.cs
  PetCenter/PetCenter/WPF/BaseViewModels/PostViewModel.cs
  PetCenter/PetCenter/WPF/BaseViewModels/RequestViewModel.cs
  PetCenter/PetCenter/WPF/BaseViewModels/ReviewViewModel.cs
  PetCenter/PetCenter/WPF/MVVM/CommandBase.cs
  PetCenter/PetCenter/WPF/MVVM/NavigableWindow.cs
  PetCenter/PetCenter/WPF/MVVM/NavigationCommand.cs
  PetCenter/PetCenter/WPF/MVVM/RelayCommand.cs
  PetCenter/PetCenter/WPF/MVVM/ViewModelBase.cs
  PetCenter/PetCenter/WPF/ViewModels/MainViewModel.cs
  PetCenter/PetCenter/WPF/ViewModels/Test1ViewModel.cs
  PetCenter/PetCenter/WPF/ViewModels/Test2ViewModel.cs
  PetCenter/PetCenter/WPF/Views/MainWindow.xaml
  PetCenter/PetCenter/WPF/Views/MainWindow.xaml.cs
  PetCenter/PetCenter/WPF/Views/Test1View.xaml
  PetCenter/PetCenter/WPF/Views/Test1View.xaml.cs
  PetCenter/PetCenter/WPF/Views/Test2View.xaml
  PetCenter/PetCenter/WPF/Views/Test2View.xaml.cs
Labels: enhancement

#26 Posts - Comment and Likes [FULL]
  PetCenter/PetCenter/App.xaml
  PetCenter/PetCenter/App.xaml.cs
  PetCenter/PetCenter/Core/Service/LoginService.cs
  PetCenter/PetCenter/Core/Service/PostService.cs
  PetCenter/PetCenter/Core/Stores/AuthenticationStore.cs
  PetCenter/PetCenter/Domain/Model/Comment.cs
  PetCenter/PetCenter/Domain/Model/Person.cs
  PetCenter/PetCenter/Domain/RepositoryInterfaces/ICrud.cs
  PetCenter/PetCenter/Domain/RepositoryInterfaces/IPostRepository.cs
  PetCenter/PetCenter/Domain/State/Accepted.cs
  PetCenter/PetCenter/Domain/State/Adopted.cs
  PetCenter/PetCenter/Domain/State/Created.cs
  PetCenter/PetCenter/Domain/State/Declined.cs
  PetCenter/PetCenter/Domain/State/Hidden.cs
  PetCenter/PetCenter/Domain/State/OnHold.cs
  PetCenter/PetCenter/Domain/State/TemporaryAccommodation.cs
  PetCenter/PetCenter/HostBuilders/AddServicesExtension.cs
  PetCenter/PetCenter/HostBuilders/AddStoresExtension.cs
  PetCenter/PetCenter/HostBuilders/AddViewModelsExtension.cs
  PetCenter/PetCenter/PetCenter.csproj
  PetCenter/PetCenter/Repository/AccountSqlRepository.cs
  PetCenter/PetCenter/Repository/AnimalSqlRepository.cs
  PetCenter/PetCenter/Repository/CommentSqlRepository.cs
  PetCenter/PetCenter/Repository/OfferSqlRepository.cs
  PetCenter/PetCenter/Repository/PersonSqlRepository.cs
  PetCenter/PetCenter/Repository/PostSqlRepository.cs
  PetCenter/PetCenter/Repository/RequestSqlRepository.cs
  PetCenter/PetCenter/Repository/SqlRepository.cs
  PetCenter/PetCenter/WPF/BaseViewModels/PostViewModel.cs
  PetCenter/PetCenter/WPF/Components/CommentCard.xaml
  PetCenter/PetCenter/WPF/Components/CommentCard.xaml.cs
  PetCenter/PetCenter/WPF/Components/PostCard.xaml
  PetCenter/PetCenter/WPF/Components/PostCard.xaml.cs
  PetCenter/PetCenter/WPF/Converters/EnumToStringConverter.cs
  PetCenter/PetCenter/WPF/MVVM/NavigationCommand.cs
  PetCenter/PetCenter/WPF/MVVM/RelayCommand.cs
  PetCenter/PetCenter/WPF/Style/Colors.xaml
  PetCenter/PetCenter/WPF/ViewModels/PostListingViewModel.cs
  PetCenter/PetCenter/WPF/ViewModels/Test1ViewModel.cs
  PetCenter/PetCenter/WPF/ViewModels/Test2ViewModel.cs
  PetCenter/PetCenter/WPF/Views/MainWindow.xaml
  PetCenter/PetCenter/WPF/Views/PostListingView.xaml
  PetCenter/PetCenter/WPF/Views/PostListingView.xaml.cs
Labels: enhancement

#30 Post creation
  PetCenter/PetCenter/App.xaml
  PetCenter/PetCenter/App.xaml.cs
  PetCenter/PetCenter/Core/Service/AnimalTypeService.cs
  PetCenter/PetCenter/Domain/Model/Animal.cs
  PetCenter/PetCenter/Domain/Model/AnimalType.cs
  PetCenter/PetCenter/HostBuilders/AddRepositoriesExtension.cs
  PetCenter/PetCenter/HostBuilders/AddServicesExtension.cs
  PetCenter/PetCenter/HostBuilders/AddViewModelsExtension.cs
  PetCenter/PetCenter/Repository/AnimalTypeSqlRepository.cs
  PetCenter/PetCenter/Repository/DataContext.cs
  PetCenter/PetCenter/Repository/PostSqlRepository.cs
  PetCenter/PetCenter/WPF/BaseViewModels/AnimalViewModel.cs
  PetCenter/PetCenter/WPF/BaseViewModels/PhotoViewModel.cs
  PetCenter/PetCenter/WPF/BaseViewModels/PostViewModel.cs
  PetCenter/PetCenter/WPF/Components/CommentCard.xaml
  PetCenter/PetCenter/WPF/Components/PostCard.xaml
  PetCenter/PetCenter/WPF/Style/ComponentStyle.xaml
  PetCenter/PetCenter/WPF/ViewModels/CreatePostViewModel.cs
  PetCenter/PetCenter/WPF/Views/CreatePostView.xaml
  PetCenter/PetCenter/WPF/Views/CreatePostView.xaml.cs
  PetCenter/PetCenter/WPF/Views/MainWindow.xaml
  PetCenter/PetCenter/WPF/Views/PostListingView.xaml
  doc/specification/main.pdf
  scripts/ddl.sql
Labels: enhancement

#27 Window navigation
  PetCenter/PetCenter/App.xaml
  PetCenter/PetCenter/App.xaml.cs
  PetCenter/PetCenter/Core/Stores/NavigationStore.cs
  PetCenter/PetCenter/Core/Util/INavigationService.cs
  PetCenter/PetCenter/Core/Util/NavigationService.cs
  PetCenter/PetCenter/Domain/Enumerations/ViewType.cs
  PetCenter/PetCenter/Domain/Enumerations/WindowType.cs
  PetCenter/PetCenter/HostBuilders/AddServicesExtension.cs
  PetCenter/PetCenter/HostBuilders/AddViewModelsExtension.cs
  PetCenter/PetCenter/HostBuilders/AddWindowsExtension.cs
  PetCenter/PetCenter/WPF/MVVM/CreateViewModel.cs
  PetCenter/PetCenter/WPF/MVVM/IWindowFactory.cs
  PetCenter/PetCenter/WPF/MVVM/NavigableWindow.cs
  PetCenter/PetCenter/WPF/MVVM/NavigationCommand.cs
  PetCenter/PetCenter/WPF/MVVM/ViewModelFactory.cs
  PetCenter/PetCenter/WPF/MVVM/WindowFactory.cs
  PetCenter/PetCenter/WPF/Style/Buttons.xaml
  PetCenter/PetCenter/WPF/Style/Colors.xaml
  PetCenter/PetCenter/WPF/ViewModels/Administrator/AdministratorViewModel.cs
  PetCenter/PetCenter/WPF/ViewModels/Authentication/AuthenticationViewModel.cs
  PetCenter/PetCenter/WPF/ViewModels/Authentication/LoginViewModel.cs
  PetCenter/PetCenter/WPF/ViewModels/Authentication/RegisterViewModel.cs
  PetCenter/PetCenter/WPF/ViewModels/Guest/GuestViewModel.cs
  PetCenter/PetCenter/WPF/ViewModels/Guest/PostListingViewModel.cs
  PetCenter/PetCenter/WPF/ViewModels/Member/CreatePostViewModel.cs
  PetCenter/PetCenter/WPF/ViewModels/Member/MemberViewModel.cs
  PetCenter/PetCenter/WPF/ViewModels/Test1ViewModel.cs
  PetCenter/PetCenter/WPF/ViewModels/Test2ViewModel.cs
  PetCenter/PetCenter/WPF/ViewModels/Volunteer/VolunteerViewModel.cs
  PetCenter/PetCenter/WPF/Views/Administrator/AdministratorWindow.xaml
  PetCenter/PetCenter/WPF/Views/Administrator/AdministratorWindow.xaml.cs
  PetCenter/PetCenter/WPF/Views/Authentication/AuthenticationWindow.xaml
  PetCenter/PetCenter/WPF/Views/Authentication/AuthenticationWindow.xaml.cs
  PetCenter/PetCenter/WPF/Views/Authentication/LoginView.xaml
  PetCenter/PetCenter/WPF/Views/Authentication/LoginView.xaml.cs
  PetCenter/PetCenter/WPF/Views/Authentication/RegisterView.xaml
  PetCenter/PetCenter/WPF/Views/Authentication/RegisterView.xaml.cs
  PetCenter/PetCenter/WPF/Views/Guest/GuestWindow.xaml
  PetCenter/PetCenter/WPF/Views/Guest/GuestWindow.xaml.cs
  PetCenter/PetCenter/WPF/Views/Guest/PostListingView.xaml
  PetCenter/PetCenter/WPF/Views/Guest/PostListingView.xaml.cs
  PetCenter/PetCenter/WPF/Views/MainWindow.xaml
  PetCenter/PetCenter/WPF/Views/Member/CreatePostView.xaml
  PetCenter/PetCenter/WPF/Views/Member/CreatePostView.xaml.cs
  PetCenter/PetCenter/WPF/Views/Member/MemberWindow.xaml
  PetCenter/PetCenter/WPF/Views/Member/MemberWindow.xaml.cs
  PetCenter/PetCenter/WPF/Views/Test1View.xaml
  PetCenter/PetCenter/WPF/Views/Test2View.xaml
  PetCenter/PetCenter/WPF/Views/Volunteer/VolunteerWindow.xaml
  PetCenter/PetCenter/WPF/Views/Volunteer/VolunteerWindow.xaml.cs
Labels: enhancement

#39 Specification
  doc/diagrams/diagrams.mdzip
  doc/diagrams/diagrams.mdzip.bak
  doc/specification/content.tex
  doc/specification/img/adoption.jpg
  doc/specification/img/class.jpg
  doc/specification/img/load_donation.jpg
  doc/specification/img/new_posts-sequence.jpg
  doc/specification/img/send_offer.jpg
  doc/specification/img/use-case.jpg
  doc/specification/main.pdf
  doc/specification/main.tex
  doc/specification/sections/dijagram_klase.tex
  doc/specification/sections/dijagram_prelaza_stanja.tex
  doc/specification/sections/dijagram_slucajeva_koriscenja.tex
  doc/specification/sections/dijagrami_aktivnosti.tex
  doc/specification/sections/dijagrami_sekvence.tex
  doc/specification/sections/funkcionalni_zahtevi.tex
  doc/specification/sections/implementacija.tex
  doc/specification/sections/koriscene_tehnologije.tex
  doc/specification/sections/uvod.tex
Labels: documentation

#40 Add notifications view
  PetCenter/PetCenter/App.xaml.cs
  PetCenter/PetCenter/Core/Service/NotificationService.cs
  PetCenter/PetCenter/Domain/Enumerations/ViewType.cs
  PetCenter/PetCenter/Domain/RepositoryInterfaces/INotificationRepository.cs
  PetCenter/PetCenter/HostBuilders/AddViewModelsExtension.cs
  PetCenter/PetCenter/Repository/NotificationSqlRepository.cs
  PetCenter/PetCenter/WPF/BaseViewModels/NotificationViewModel.cs
  PetCenter/PetCenter/WPF/Components/NotificationCard.xaml
  PetCenter/PetCenter/WPF/Components/NotificationCard.xaml.cs
  PetCenter/PetCenter/WPF/MVVM/ViewModelFactory.cs
  PetCenter/PetCenter/WPF/ViewModels/Authentication/LoginViewModel.cs
  PetCenter/PetCenter/WPF/ViewModels/Member/MemberViewModel.cs
  PetCenter/PetCenter/WPF/ViewModels/Member/NotificationListingViewModel.cs
  PetCenter/PetCenter/WPF/ViewModels/Volunteer/VolunteerViewModel.cs
  PetCenter/PetCenter/WPF/Views/Guest/PostListingView.xaml
  PetCenter/PetCenter/WPF/Views/Member/MemberWindow.xaml
  PetCenter/PetCenter/WPF/Views/Member/NotificationListingView.xaml
  PetCenter/PetCenter/WPF/Views/Member/NotificationListingView.xaml.cs
  PetCenter/PetCenter/WPF/Views/Volunteer/VolunteerWindow.xaml
Labels: enhancement

#41 Fix registration birth date failing to convert
  PetCenter/PetCenter/WPF/BaseViewModels/PersonViewModel.cs
  PetCenter/PetCenter/WPF/ViewModels/Authentication/RegisterViewModel.cs
  PetCenter/PetCenter/WPF/Views/Authentication/RegisterView.xaml
  PetCenter/PetCenter/WPF/Views/Authentication/RegisterView.xaml.cs
Labels: bug

#46 Accepting and Declining posts
  PetCenter/PetCenter/Core/Service/PostService.cs
  PetCenter/PetCenter/Domain/Enumerations/ViewType.cs
  PetCenter/PetCenter/HostBuilders/AddViewModelsExtension.cs
  PetCenter/PetCenter/WPF/Components/PostCard.xaml
  PetCenter/PetCenter/WPF/Components/PostReviewCard.xaml
  PetCenter/PetCenter/WPF/Components/PostReviewCard.xaml.cs
  PetCenter/PetCenter/WPF/MVVM/ViewModelFactory.cs
  PetCenter/PetCenter/WPF/ViewModels/Guest/PostListingViewModel.cs
  PetCenter/PetCenter/WPF/ViewModels/Volunteer/PostReviewViewModel.cs
  PetCenter/PetCenter/WPF/ViewModels/Volunteer/VolunteerViewModel.cs
  PetCenter/PetCenter/WPF/Views/Volunteer/PostReviewView.xaml
  PetCenter/PetCenter/WPF/Views/Volunteer/PostReviewView.xaml.cs
  PetCenter/PetCenter/WPF/Views/Volunteer/VolunteerWindow.xaml
Labels: enhancement

#50 Specification
  doc/diagrams/diagrams.mdzip
  doc/diagrams/diagrams.mdzip.bak
  doc/specification/img/hide-post.jpg
  doc/specification/img/login.jpg
  doc/specification/main.pdf
  doc/specification/sections/dijagrami_aktivnosti.tex
  doc/specification/sections/dijagrami_sekvence.tex
  doc/specification/sections/implementacija.tex
  doc/specification/sections/nefunkcionalni_zahtevi.tex
  doc/specification/sections/uvod.tex
Labels: documentation

#53 Requests
  PetCenter/PetCenter/Core/Service/RequestService.cs
  PetCenter/PetCenter/Domain/Constants.cs
  PetCenter/PetCenter/Domain/Enumerations/ViewType.cs
  PetCenter/PetCenter/Domain/Model/Request.cs
  PetCenter/PetCenter/Domain/RepositoryInterfaces/IRequestRepository.cs
  PetCenter/PetCenter/HostBuilders/AddServicesExtension.cs
  PetCenter/PetCenter/HostBuilders/AddViewModelsExtension.cs
  PetCenter/PetCenter/Repository/RequestSqlRepository.cs
  PetCenter/PetCenter/WPF/BaseViewModels/RequestViewModel.cs
  PetCenter/PetCenter/WPF/Components/RequestCard.xaml
  PetCenter/PetCenter/WPF/Components/RequestCard.xaml.cs
  PetCenter/PetCenter/WPF/MVVM/ViewModelFactory.cs
  PetCenter/PetCenter/WPF/ViewModels/Member/MemberViewModel.cs
  PetCenter/PetCenter/WPF/ViewModels/Volunteer/RequestListingViewModel.cs
  PetCenter/PetCenter/WPF/ViewModels/Volunteer/VolunteerViewModel.cs
  PetCenter/PetCenter/WPF/Views/Member/MemberWindow.xaml
  PetCenter/PetCenter/WPF/Views/Volunteer/RequestListingView.xaml
  PetCenter/PetCenter/WPF/Views/Volunteer/RequestListingView.xaml.cs
  PetCenter/PetCenter/WPF/Views/Volunteer/VolunteerWindow.xaml
Labels: enhancement
